apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: {{ .Values.namespace }}
data:
  init-schemas.sql: |
    CREATE SCHEMA IF NOT EXISTS ducklake;
    CREATE SCHEMA IF NOT EXISTS platform;
