spark.master local[*]
spark.sql.adaptive.enabled true
spark.sql.adaptive.coalescePartitions.enabled true
spark.eventLog.enabled true
spark.eventLog.dir /tmp/spark-events
spark.history.fs.logDirectory /tmp/spark-events
spark.connect.grpc.binding.host 0.0.0.0
spark.connect.grpc.binding.port 15002
spark.driver.memory 2g
spark.executor.memory 2g
